### PR TITLE
Default headers

### LINKED ISSUE #51: Default headers
I am porting my second library to FluentHttpClient and noticed a missing feature: I can't set a default header that gets automatically added to every request. I know that I can invoke the `IRequest.WithHeader(string key, string value)` for each request, but it's very tedious.

I propose adding a method to IFluentClient like so:
```CSharp
        /// <summary>Adds a header which should be sent with each request.</summary>
        /// <param name="name">The name of the header.</param>
        /// <param name="value">The value of the header.</param>
        public IClient SetHeader(string name, string value)
        {
            this.BaseClient.DefaultRequestHeaders.Add(name, value);
            return this;
        }
```

### PR DESCRIPTION
**Pull request by Jericho**
Resolves #51

### CODE REVIEW

**Comment by Pathoschild** [comment]
I'm fine with the method itself, but I'm not sure the `SetX` convention is intuitive for headers. It implies there's one header with subsequent calls superceding (which is how the other `SetX` methods work), when really each call just adds another header. I'm not sure what to use instead though; maybe `client.AddDefaultHeader`?

**Comment by Jericho** [comment]
How about we change the logic in the SetHeader method to ensure that subsequent calls overwrite the header? By the way, one thing that wasn't obvious to me but I recently figured out: developers can add headers directly to the underlying HttpClient like so: `client.BaseClient.DefaultRequestHeaders.Add("myHeader", "abc123");`.

Since you bring up 'Default': I also have wondered if we should add `Default` to all `SetXXX` methods on IClient that can be overridden by a `WithXXX` call? So for example, `SetDefaultAuthentication` instead of `SetAuthentication`. I think I prefer to leave it out, and to make method names shorter.

**Comment by Jericho** [comment]
Or, even better how about both `AddHeader` and `SetHeader`?

**Comment by Pathoschild** [comment]
Pending discussion in #51.

**Pull request closed without merging**
