### PR TITLE
Authentication

### LINKED ISSUE #10: There's no easy way to specify authentication
The readme says that I can create my own implementation of IHttpFilter for authentication but this means that every developer using FluentHttpClient must "reinvent the wheel" for this simple task. Since most API require some form of authentication, I believe FluentHttpClient should make it easier to provide authentication.

I propose the following:

#### We should be able to configure authentication for each request
1. I suggest adding `IRequest WithAuthentication(string scheme, string value);` to IRequest (and Request.cs of course).
2. Add convenient methods for the most common authentication schemes. The two that I have most frequently seen are: 'bearer' (which is when you provide an api key) and 'basic' (which is when you provide a username and password). These two methods would be called `WithBearerAuthentication` and `WithBasicAuthentication` and would simply invoke the `WithAuthentication` method with appropriate parameters.

#### We should also be able to configure authentication for the client
3. I suggest adding a new IHttpFilter called `AuthorizationFilter`. This filter would automatically add the authentication to every request
4. I suggest adding `public void AddAuthentication(string scheme, string value);` to IClient (and FluentClient.cs of course). This method would instantiate a new `AuthenticationFilter` with provided parameters and add it to the list of filters.
5. Add convenient methods for the most common authentication schemes. As I previously mentioned, the two that I think are the most common are 'bearer' and 'basic'. These two methods would be called `AddBearerAuthentication` and `AddBasicAuthentication` and would simply invoke the `AddAuthentication` method with appropriate parameters.

I will be away for a while but I volunteer to submit a PR to add this functionality when I return.

### PR DESCRIPTION
**Pull request by Jericho**
Add methods on the IClient and IRequest interfaces that allow developers to specify the authentication scheme they want to use and implement these methods in the FluentClient and the Request classes. Also, add convenient extension methods for some of the most commonly used authentication schemes.

Resolves #10

### CODE REVIEW

**Comment by Jericho** [comment]
@Pathoschild I rebased my branch which resolved all conflicts. This is ready to be merged.

**Comment by Jericho** [comment]
Whenever you're ready, this PR is ready to be merged

**Comment by Pathoschild** [comment]
Sorry for the delay, I'm catching up on projects after the holidays. Reviewing all your PRs is near the top of my to-do list:
to-do list

**Comment by Pathoschild** [comment]
This looks fine overall. A few review notes:

* Some of the methods seem to be duplicated, probably due to a merge conflict. For example,  `FluentClient` has two identical `SetAuthentication` methods.
* The `SetAuthentication` and `SetUserAgent` methods on `IClient` should be chainable so you can configure them fluently:
  ```cs
  var client = new FluentClient(…)
     .SetUserAgent(…)
     .SetAuthentication(…);
  ```
* `Set/WithAuthentication` is great and I'm fine with `Set/WithBasicAuthentication` because it involves some extra work, but `Set/WithBearerAuthentication(key)` is just a wrapper for `Set/WithAuthentication("bearer", key)`. I'm not convinced the extra bearer methods add any discoverability or convenience over the original method. That's not to say I'm strictly opposed to it, but I'd like to know more about the reasoning for including a separate method for bearer authentication over other schemes.

**Comment by Jericho** [comment]
1. Regarding duplicates: the duplicate `SetAuthentication` method is probably the result of an issue when I rebased the branch. I also noticed that `WithBasicAuthentication` and `WithBearerAuthentication` extension methods are also duplicated. I'll remove the dupes.

2. Regarding chainability: agreed. I'll fix it.

3. Regarding `WithBearerAuthentication`: it is indeed just a wrapper around `WithAuthentication` but the reason why I think it's valuable is because it saves developers from having to remember the name of the scheme. This authentication scheme is commonly used in APIs that require developers to provide an API key and therefore I want to prevent developers having to specify the _magic_ string `"Bearer"`.

**Comment by Pathoschild** [comment]
The scheme does seem common for OAuth 2.0 APIs, so I guess it's fine. Merged into `develop` for the upcoming 2.4 release. Thanks!

**Pull request merged**
