### PR TITLE
Add cancellation token to async methods

### LINKED ISSUE #24: Async methods should accept a concellation token
The cancellation token allows a long running async method to be cancelled but the FluentClient currently does not accept such a token. I propose adding a parameter for the token to methods such as `DeleteAsync`, `GetAsync`, `SendAsync`, etc.. Of course this parameter should be optional.

I will submit a PR.

### PR DESCRIPTION
**Pull request by Jericho**
Resolves #24

### CODE REVIEW

**Comment by Pathoschild** [comment]
Supporting cancellation tokens is fine, but I wonder if this will confuse users:
image

We could maybe make the argument nullable and expand the documentation a bit:
  image

...but I think a new fluent method might be cleaner, since it keeps the main use case focused, it's simple if you need it, and it's also more flexible since you can set the cancellation token later:
  ```cs
  client
     .GetAsync("...")
     .WithCancellationToken(token)
     .AsString();
  ```

What do you think?

**Comment by Jericho** [comment]
The reason I used the `default(CancellationToken)` syntax is because that's the syntax I use in my libraries ([example](https://github.com/Jericho/StrongGrid/blob/master/Source/StrongGrid/Resources/Contacts.cs#L149)) and I haven't received any complaints about confusion, also it's the syntax used by many other libraries ([example](https://github.com/smiggleworth/Stripe.Client/blob/7ac6f30eae40f0a0b37a2cfa6f57171de4a95460/src/Stripe.Client.Sdk/Clients/Core/ICustomerClient.cs#L15), [example](https://github.com/tmds/Tmds.DBus/blob/7e7f50d93ac280b038588d605e9cb5e325c821b3/src/Tmds.DBus/IConnection.cs#L16), [example](https://github.com/csongysun/blogs/blob/cfda01753b019311fde35597de8fab2d1330df72/src/blogs/Identity/IRoleClaimStore.cs#L13)) and it's also the syntax used by Microsoft ([example](https://github.com/MobileEssentials/Roslyn/blob/c59e9a03c69a0116001cd397d6882dcc644230c5/Src/Workspaces/CoreTest/Host/WorkspaceServices/TemporaryStorage/TestTemporaryStorage.cs#L18), [example](https://github.com/Microsoft/RTVS/blob/0df4026738d626204dc1c46ecf4a83b3db7a444b/src/Host/Client/Impl/Definitions/IMessageTransport.cs#L11), [example](https://github.com/mono/roslyn/blob/f4ef9144d8357f7af6a72992333ef162b5f1d552/src/Workspaces/CoreTest/Host/WorkspaceServices/TemporaryStorage/TestTemporaryStorage.cs#L18)).

There are instances where Microsoft has opted for overloads like so:
```CSharp
public Task<int> ReadAsync(Byte[] buffer, int offset, int count)
{
    return ReadAsync(buffer, offset, count, CancellationToken.None);
}
public virtual Task<int> ReadAsync(Byte[] buffer, int offset, int count, CancellationToken cancellationToken)
{
    ... snip ...
}
```
but I find it annoying to have to create and maintain two overloads for all async methods.

Having said that, I like your idea of a fluent `WithCancellationToken` method. Let me see if I can figure out how to implement this idea.

**Comment by Jericho** [comment]
Turned out to be easier than I expected to add a fluent `WithCancellationToken` method.

**Comment by Pathoschild** [comment]
Looks good. Merged into `develop` for the upcoming 2.4 release. Thanks!

**Pull request merged**
